spring.application.name=auth
spring.datasource.url=jdbc:postgresql://localhost:5432/eccomerce
spring.datasource.username=postgres
spring.datasource.password=Solano3030?

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=TVT1QiD0JC5TojjXIqw0fMpSwtKGoQ0GpAH7GNgrSiY=
jwt.expiration=86400000